#!/usr/bin/env python3
"""
Scan experiments/{slug}/ directories and build a single dashboard page that
links to each experiment's report and viewpoint gallery.

Usage:
  python build_dashboard.py [experiments_dir] [out_path]

Defaults: experiments_dir="experiments", out_path="{experiments_dir}/index.html"

Per experiment (a subdirectory of experiments_dir containing report.md), reads:
  {slug}/report.md            -> hypothesis (from "# Experiment: ..." heading)
                                  and verdict (from "**Verdict:** ...")
  {slug}/gallery/index.html   -> first embedded <img src="data:..."> as a thumbnail

A subdirectory without report.md is skipped (not yet a finished experiment). A
missing gallery/index.html just renders the card without a thumbnail and with
the Gallery link disabled — the report may still exist on its own.
"""
import sys, os, re, html

CSS = """
:root {
  --bg-page: #f6f5f1; --bg: #faf9f5; --ink: #2a2920; --ink-2: #6c675f;
  --muted: #858179; --line: #e0ddd8; --line-strong: #a8a49c; --accent: #9a4929;
  --mono: "JetBrains Mono", ui-monospace, "SF Mono", "Cascadia Code", Consolas, monospace;
  --serif: Charter, "Iowan Old Style", "Palatino Linotype", Georgia, serif;
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
    --bg-page: #191918; --bg: #262624; --ink: #e8e4dc; --ink-2: #938e87;
    --muted: #5a5955; --line: #333330; --line-strong: #636360; --accent: #d97757;
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
  --bg-page: #191918; --bg: #262624; --ink: #e8e4dc; --ink-2: #938e87;
  --muted: #5a5955; --line: #333330; --line-strong: #636360; --accent: #d97757;
  color-scheme: dark;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg-page); color: var(--ink); font-family: var(--serif);
  font-size: 1.05rem; line-height: 1.65; text-align: center; -webkit-font-smoothing: antialiased;
}
.wrap { width: 1080px; max-width: 100%; margin: 0 auto; padding: 4rem 1.5rem 6rem; }
.eyebrow {
  font-family: var(--mono); font-size: 0.92rem; letter-spacing: 0.12em;
  text-transform: uppercase; color: var(--accent); margin: 0 0 0.9rem;
}
h1 {
  font-family: var(--mono); font-weight: 600; font-size: clamp(1.6rem, 3.2vw, 2.1rem);
  line-height: 1.25; margin: 0 0 0.6rem; text-wrap: balance; letter-spacing: -0.01em;
}
.dek { color: var(--ink-2); font-size: 1.05rem; max-width: 90ch; margin: 0 auto 3rem; }
.grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.6rem; text-align: left;
}
.card {
  border: 1px solid var(--line); border-radius: 4px; background: var(--bg);
  overflow: hidden; display: flex; flex-direction: column;
}
.thumb { border-bottom: 1px solid var(--line); background: var(--bg-page); aspect-ratio: 16/10; display: flex; align-items: center; justify-content: center; }
.thumb img { display: block; width: 100%; height: 100%; object-fit: cover; }
.thumb .no-thumb { font-family: var(--mono); font-size: 0.82rem; color: var(--muted); }
.body { padding: 1.2rem 1.3rem 1.4rem; display: flex; flex-direction: column; gap: 0.6rem; flex: 1; }
.badge {
  align-self: flex-start; font-family: var(--mono); font-size: 0.76rem; text-transform: uppercase;
  letter-spacing: 0.06em; padding: 0.2rem 0.55rem; border-radius: 2px; border: 1px solid currentColor;
}
.badge.supported { color: #2f8f4e; }
.badge.refuted { color: #b3453f; }
.badge.inconclusive { color: #a3821f; }
.badge.unknown { color: var(--muted); }
h3 { font-family: var(--mono); font-size: 1.02rem; font-weight: 600; margin: 0; letter-spacing: -0.01em; line-height: 1.4; }
.slug { font-family: var(--mono); font-size: 0.8rem; color: var(--muted); }
.links { margin-top: auto; padding-top: 0.6rem; display: flex; gap: 1rem; font-family: var(--mono); font-size: 0.86rem; }
.links a { color: var(--accent); text-decoration: none; }
.links a:hover { text-decoration: underline; }
.links .disabled { color: var(--muted); }
.empty { border: 1px dashed var(--line-strong); border-radius: 4px; padding: 3rem 1.5rem; color: var(--ink-2); font-family: var(--mono); font-size: 0.95rem; }
footer { margin-top: 3.5rem; padding-top: 1.6rem; border-top: 1px solid var(--line); font-size: 0.95rem; color: var(--ink-2); }
"""

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Experiments Dashboard</title>
<style>{css}</style>
</head>
<body>
<div class="wrap">
  <p class="eyebrow">goal-init &middot; experiments dashboard</p>
  <h1>Experiments</h1>
  <p class="dek">{dek}</p>
  {body}
  <footer>Regenerated by <code>goal-init/scripts/build_dashboard.py</code> &mdash; also run automatically at the end of <code>/experiment</code>.</footer>
</div>
</body>
</html>
"""


def parse_report(path):
    text = open(path, encoding="utf-8").read()
    title_m = re.search(r"^#\s*Experiment:\s*(.+)$", text, re.MULTILINE)
    verdict_m = re.search(r"\*\*Verdict:\*\*\s*(\w+)", text)
    hypothesis = title_m.group(1).strip() if title_m else "(untitled experiment)"
    verdict = verdict_m.group(1).strip() if verdict_m else "Unknown"
    return hypothesis, verdict


def first_thumbnail(gallery_index_path):
    if not os.path.exists(gallery_index_path):
        return None
    text = open(gallery_index_path, encoding="utf-8").read()
    m = re.search(r'<img[^>]+src="(data:[^"]+)"', text)
    return m.group(1) if m else None


def card_html(slug, hypothesis, verdict, thumb, has_gallery):
    badge_class = verdict.lower() if verdict.lower() in ("supported", "refuted", "inconclusive") else "unknown"
    thumb_html = (
        f'<img src="{thumb}" alt="{html.escape(slug)} preview" loading="lazy">'
        if thumb else '<span class="no-thumb">no gallery yet</span>'
    )
    gallery_link = (
        f'<a href="{html.escape(slug)}/gallery/index.html">Gallery</a>'
        if has_gallery else '<span class="disabled">Gallery</span>'
    )
    return f'''
    <article class="card">
      <div class="thumb">{thumb_html}</div>
      <div class="body">
        <span class="badge {badge_class}">{html.escape(verdict)}</span>
        <h3>{html.escape(hypothesis)}</h3>
        <div class="slug">{html.escape(slug)}</div>
        <div class="links"><a href="{html.escape(slug)}/report.md">Report</a>{gallery_link}</div>
      </div>
    </article>'''


def main():
    experiments_dir = sys.argv[1] if len(sys.argv) > 1 else "experiments"
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(experiments_dir, "index.html")

    slugs = []
    if os.path.isdir(experiments_dir):
        slugs = sorted(
            d for d in os.listdir(experiments_dir)
            if os.path.isdir(os.path.join(experiments_dir, d))
            and os.path.exists(os.path.join(experiments_dir, d, "report.md"))
        )

    cards = []
    for slug in slugs:
        base = os.path.join(experiments_dir, slug)
        hypothesis, verdict = parse_report(os.path.join(base, "report.md"))
        gallery_index = os.path.join(base, "gallery", "index.html")
        has_gallery = os.path.exists(gallery_index)
        thumb = first_thumbnail(gallery_index)
        cards.append(card_html(slug, hypothesis, verdict, thumb, has_gallery))

    if cards:
        dek = f"{len(cards)} experiment{'s' if len(cards) != 1 else ''} run so far, newest verdicts and viewpoint galleries below."
        body = f'<div class="grid">{"".join(cards)}</div>'
    else:
        dek = "No experiments yet."
        body = '<div class="empty">Run <code>/experiment</code> to produce the first one.</div>'

    out = TEMPLATE.format(css=CSS, dek=html.escape(dek), body=body)

    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {out_path} ({len(cards)} experiments)")


if __name__ == "__main__":
    main()
